### ISSUE TITLE
org.apache.commons.lang.UnhandledException

### ISSUE THREAD

**Issue by tomo1560** [misterT2525/HeadDictionary#1]
起動時と一定時間ごとにエラーが表示されました。
ProtocolLibは最新開発版、Spigotフォーラムに上げられていたものどちらもためしてみましましたが同じエラーが発生しました。
実際の動作には問題はないです。
### 使用したSpigot :

spigot versionCraftBukkit version git-Spigot-6f291ea-55a8535 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)
### 使用したプラグイン :

ProtocolLib v3.7.0-SNAPSHOT-b258 または ProtocolLib v3.7.0-BETA
HeadDictionary v1.0.0-SNAPSHOT-cc9cfa5  
### Javaのバージョン :

Java 1.8.0_74 x64
### 起動時のエラーログ

`[05:18:04] [Server thread/INFO]: [HeadDictionary] Enabling HeadDictionary v1.0.0-SNAPSHOT-cc9cfa5
[05:18:04] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[05:18:04] [Server thread/INFO]: Done (2.009s)! For help, type "help" or "?"
[05:18:04] [Craft Scheduler Thread - 0/INFO]: [Metrics] Prepared request for ProtocolLib uncompressed=294 compressed=239
[05:18:04] [Craft Scheduler Thread - 1/WARN]: Exception in thread "Craft Scheduler Thread - 1" 
[05:18:04] [Craft Scheduler Thread - 1/WARN]: org.apache.commons.lang.UnhandledException: Plugin HeadDictionary v1.0.0-SNAPSHOT-cc9cfa5 generated an exception while executing task 4
    at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
    at net.mistertgroup.headdictionary.Metrics.postPlugin(Metrics.java:335)
    at net.mistertgroup.headdictionary.Metrics.access$400(Metrics.java:57)
    at net.mistertgroup.headdictionary.Metrics$1.run(Metrics.java:223)
    at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more
`

**Comment by misterT2525** [comment]
エラーログを見る限り、Metricsの問題だと思います。
一時的な対策として、`plugins/PluginMetrics/config.yml`内の`opt-out`を`true`にすることでエラーが発生しなくなると思います。

追記: 不具合を修正したので、最新版に更新することで、上記の対策をしなくても問題ありません。
